### ISSUE TITLE
Crashing with null language providers

### ISSUE THREAD

**Issue by jakepurple13** [Qawaz/compose-code-editor#18]
I'm trying to show XML but I keep running into:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Missing language for extension : 
	at com.wakaztahir.codeeditor.prettify.parser.Prettify.getLangFromExtension(Prettify.kt:137)
	at com.wakaztahir.codeeditor.prettify.parser.Prettify.getLexerForExtension(Prettify.kt:404)
	at com.wakaztahir.codeeditor.prettify.parser.Prettify$CreateSimpleLexer.decorate(Prettify.kt:792)
	at com.wakaztahir.codeeditor.prettify.PrettifyParser.parse(PrettifyParser.kt:25)
	at com.wakaztahir.codeeditor.prettify.PrettifyParser.parse(PrettifyParser.kt:21)
```

**Comment by wakaztahir** [comment]
You should use `html` as `xml` may not be supported. XML is like HTML but not supported at the moment.
Tts very hard to develop a code editor or syntax highlighter that works with all languages and is small, If you are looking for something special you may have to write it.

**Comment by jakepurple13** [comment]
I'm getting the same thing when I use HTML:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Missing language for extension : 
	at com.wakaztahir.codeeditor.prettify.parser.Prettify.getLangFromExtension(Prettify.kt:137)
	at com.wakaztahir.codeeditor.prettify.parser.Prettify.getLexerForExtension(Prettify.kt:404)
	at com.wakaztahir.codeeditor.prettify.parser.Prettify$CreateSimpleLexer.decorate(Prettify.kt:792)
	at com.wakaztahir.codeeditor.prettify.PrettifyParser.parse(PrettifyParser.kt:25)
	at com.wakaztahir.codeeditor.prettify.PrettifyParser.parse(PrettifyParser.kt:18)
	at com.wakaztahir.codeeditor.utils.AnnotationKt.parseCodeAsAnnotatedString(Annotation.kt:21)
	at com.wakaztahir.codeeditor.utils.AnnotationKt.parseCodeAsAnnotatedString(Annotation.kt:30)
```

**Comment by wakaztahir** [comment]
Could you please try using the Enum instead of extension, I'm pretty sure it contains html extension.

**Comment by jakepurple13** [comment]
That is what I'm doing.
```kotlin
val parsedCode = remember(svgText, language) {
                            parseCodeAsAnnotatedString(
                                parser = parser,
                                theme = theme,
                                lang = CodeLang.XML,
                                code = svgText
                            )
}
```
And it still crashes. Even when using HTML.
